language: php
# The Travis CI container mode has random functional test fails, so we must use
# sudo here.
sudo: true

php:
  - 7.1
  - 7.2

matrix:
  # Don't wait for the allowed failures to build.
  fast_finish: true

# Cache composer downloads because cloning Coder form drupal.org is very slow :-(
cache:
  directories:
    - $HOME/.composer

before_script:
  # Remove Xdebug as we don't need it and it causes
  # PHP Fatal error:  Maximum function nesting level of '256' reached.
  # We also don't care if that file exists or not on PHP 7.
  - phpenv config-rm xdebug.ini || true

  # Remember the current rules test directory for later use in the Drupal
  # installation.
  - composer install

script:
  # Run the PHPUnit tests and code style checks.
  - ./vendor/bin/phpunit
