name: CI tests for Multisite request matcher

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies with composer
        uses: drunomics/composer

      - name: PHPUnit Tests
        uses: drunomics/phpunit
        with:
          configuration: phpunit.xml.dist
          args: --coverage-text
          version: 7.5
